export const GET_BUDGETS = "GET_BUDGETS";
export const ADD_BUDGET = "ADD_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const GET_SINGLE_BUDGET = "GET_SINGLE_BUDGET";
